### PR TITLE
Make state poll interval configurable

### PR DESCRIPTION
**Pull request by rollebolle**
The interval in which the state is polled is configurable via a command line parameter or via the config file.

### CODE REVIEW

**Review by kubalewski — CHANGES_REQUESTED** [review]
Hi Roland!

Many thanks for this PR.

One general comment, we do create PRs against dev branch, once it is merged into dev, it would get into main branch at point of new release.

Also a nit comment that we could improve in the code below.

Thank you!

**Comment by rollebolle** [comment]
Thanks for the comments! I have updated the PR accordingly

**Comment by mmichaliINTC** [comment]
Hi @rollebolle! We are terribly sorry, it seems we forgot about your great PR - please forgive us. Would you be so kind to rebase onto latest `dev` branch so we can proceed to final review and merging? Once again - sorry for this delay!

**Comment by kubalewski** [comment]
Same behavior merged in #42, closing.

**Pull request closed without merging**
